<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-15 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 3.2.7 on 2021-11-03 07:27

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 416b362219561641cfea6376ea860d54e82b08e7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=255, verbose_name='Customer Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('pin_code', models.CharField(max_length=255, verbose_name='Pin Code')),
                ('building_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Type')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('total_qty', models.IntegerField(verbose_name='Total Quantity')),
<<<<<<< HEAD
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date')),
=======
>>>>>>> 416b362219561641cfea6376ea860d54e82b08e7
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_user', to='users.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
