<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-15 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 3.2.7 on 2021-11-03 07:27

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 416b362219561641cfea6376ea860d54e82b08e7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
<<<<<<< HEAD
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date')),
=======
>>>>>>> 416b362219561641cfea6376ea860d54e82b08e7
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_item_product', to='products.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
